forward_velocity_offset = 0.0 #x向速度偏置
side_velocity_offset = 0.0    #y向速度偏置
stand_height = 0.33           #默认站立高度

enable_flip     = true #前空翻功能开关
enable_backflip = true #后空翻功能开关
enable_sideflip = true #侧空翻功能开关
enable_greeting = true #打招呼功能开关
enable_jump     = true #跳跃功能开关
enable_dance    = true #扭身体功能开关
enable_turnover = true #翻滚功能开关

is_default_lidar = false #是否是默认激光版
load_mass     = 0.0      #负载质量
load_x_offset = 0.0      #负载x向偏心，单位为m
load_y_offset = 0.0 	 #负载y向偏心，单位为m
load_z_offset = 0.0 	 #负载z向偏心，单位为m

sideflip_abad_kp = 70.0
sideflip_hip_kp  = 70.0
sideflip_knee_kp = 70.0

#后空翻
backflip_hip_kp  = 60.0 #后空翻空中转速
kp_carpet_comp   = 40.0 #地毯后空翻补偿

backflip_hl_hip_kp_comp = 1.0  #左右偏转补偿 （0.5~1.5）
backflip_hr_hip_kp_comp = 1.0

backflip_fl_knee_kp = 60.0
backflip_fr_knee_kp = 60.0
backflip_hl_knee_kp = 55.0
backflip_hr_knee_kp = 55.0

#前空翻
frontflip_Rev_comp  = 1.0 #前空翻空中转速补偿 （-3.0 ~ 2.0）

#向前跳
jumplong_Rev_comp   = 0.0 #向前跳空中转速补偿 （-0.2 ~ 0.1）
jumplong_left_bias  = 0.0 #左偏补偿 （-30 ~ 30）
jumplong_right_bias = 0.0 #右偏补偿 （-30 ~ 30）