#后空翻电量补偿
#high_battery_comp第一项为需要补偿的最高电量，第二项为最高电量补偿值大小
#low_battery_comp第一项为需要补偿的最低电量，第二项为最低电量补偿值大小
#电量处于需要补偿的最高电量和最低电量区间时，补偿大小为最高电量补偿值和最低电量补偿值的线性插值
#电量处于补偿区间外时，补偿大小为零
high_battery_comp: [100.0, 10.0] 
low_battery_comp: [80.0, 1.0]
